package lifting.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setMainImg(java.lang.String mainImg) {
		set("main_img", mainImg);
	}
	
	public java.lang.String getMainImg() {
		return getStr("main_img");
	}

	public void setDetailImg(java.lang.String detailImg) {
		set("detail_img", detailImg);
	}
	
	public java.lang.String getDetailImg() {
		return getStr("detail_img");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setTbUrl(java.lang.String tbUrl) {
		set("tb_url", tbUrl);
	}
	
	public java.lang.String getTbUrl() {
		return getStr("tb_url");
	}

	public void setTbProductId(java.lang.Long tbProductId) {
		set("tb_product_id", tbProductId);
	}
	
	public java.lang.Long getTbProductId() {
		return getLong("tb_product_id");
	}

	public void setTbShopId(java.lang.Long tbShopId) {
		set("tb_shop_id", tbShopId);
	}
	
	public java.lang.Long getTbShopId() {
		return getLong("tb_shop_id");
	}

	public void setTbkKey(java.lang.String tbkKey) {
		set("tbk_key", tbkKey);
	}
	
	public java.lang.String getTbkKey() {
		return getStr("tbk_key");
	}

	public void setPrice(java.lang.Long price) {
		set("price", price);
	}
	
	public java.lang.Long getPrice() {
		return getLong("price");
	}

	public void setBrandId(java.lang.Long brandId) {
		set("brand_id", brandId);
	}
	
	public java.lang.Long getBrandId() {
		return getLong("brand_id");
	}

}
