package lifting.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setMainImg(String mainImg) {
		set("main_img", mainImg);
	}

	public String getMainImg() {
		return get("main_img");
	}

	public void setDetailImg(String detailImg) {
		set("detail_img", detailImg);
	}

	public String getDetailImg() {
		return get("detail_img");
	}

	public void setContent(String content) {
		set("content", content);
	}

	public String getContent() {
		return get("content");
	}

	public void setTbUrl(String tbUrl) {
		set("tb_url", tbUrl);
	}

	public String getTbUrl() {
		return get("tb_url");
	}

	public void setTbProductId(Long tbProductId) {
		set("tb_product_id", tbProductId);
	}

	public Long getTbProductId() {
		return get("tb_product_id");
	}

	public void setTbShopId(Long tbShopId) {
		set("tb_shop_id", tbShopId);
	}

	public Long getTbShopId() {
		return get("tb_shop_id");
	}

	public void setTbkKey(String tbkKey) {
		set("tbk_key", tbkKey);
	}

	public String getTbkKey() {
		return get("tbk_key");
	}

	public void setPrice(Long price) {
		set("price", price);
	}

	public Long getPrice() {
		return get("price");
	}

	public void setBrandId(Long brandId) {
		set("brand_id", brandId);
	}

	public Long getBrandId() {
		return get("brand_id");
	}

}
