package lifting.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setMobileNum(String mobileNum) {
		set("mobile_num", mobileNum);
	}

	public String getMobileNum() {
		return get("mobile_num");
	}

	public void setLastLoginTime(String lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}

	public String getLastLoginTime() {
		return get("last_login_time");
	}

	public void setMobileType(String mobileType) {
		set("mobile_type", mobileType);
	}

	public String getMobileType() {
		return get("mobile_type");
	}

	public void setIsLocked(Integer isLocked) {
		set("is_locked", isLocked);
	}

	public Integer getIsLocked() {
		return get("is_locked");
	}

	public void setAge(Integer age) {
		set("age", age);
	}

	public Integer getAge() {
		return get("age");
	}

	public void setSex(Integer sex) {
		set("sex", sex);
	}

	public Integer getSex() {
		return get("sex");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

}
