package lifting.model;

import lifting.basemodel.BaseAttaches;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attaches extends BaseAttaches<Attaches> {
	public static final Attaches dao = new Attaches();
}
