package lifting.model;

import lifting.basemodel.BaseBrand;

import java.util.List;
import java.util.Map;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand();

	public List<Product> getProducts() {
		return Product.dao.find("select * from product where brand_id=?", get("id"));
	}

	public Map<String, Object> getBandById(long id){
		return dao.findById(id)._getAttrs();
	}
}
