package lifting.model;

import lifting.basemodel.BaseBrand;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Brand extends BaseBrand<Brand> {
	public static final Brand dao = new Brand();
}
