package lifting.model;

import lifting.basemodel.BaseProduct;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product();
}
