package lifting.model;

import lifting.basemodel.BaseProduct;

import java.util.HashMap;
import java.util.Map;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Product extends BaseProduct<Product> {
	public static final Product dao = new Product();

	private Map<String, Object> getBrand(long bandId){
		return Brand.dao.getBandById(bandId);
	}

	public Map<String, Object> getProductById(long id){
		Product product = dao.findById(id);
		Map<String, Object> map = new HashMap<>(product._getAttrs());
		map.put("band",getBrand(product.getBrandId()));
		return map;
	}

}
