package lifting.model;

import lifting.basemodel.BaseUser;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	public static final int SEX_MALE=1;//男
	public static final int SEX_FEMALE=1;//女
}
